CREATE DATABASE QLKHO;
USE QLKHO;

CREATE TABLE ROLE_TABLE(
	ID INT PRIMARY KEY,
	ROLE_NAME NVARCHAR(MAX) NOT NULL 
);

CREATE TABLE ACCOUNT(
	ID INT PRIMARY KEY, 
	ACCOUNT_NAME NVARCHAR(MAX) NOT NULL,
	EMAIL NVARCHAR(MAX) NOT NULL,
	ACCOUNT_PASSWORD NVARCHAR(MAX) NOT NULL,
	PHONE NVARCHAR(11) NULL, 
	STATUS NVARCHAR(11) NOT NULL,
	ID_ROLE INT,
	FOREIGN KEY (ID_ROLE) REFERENCES ROLE_TABLE(ID)
);

CREATE TABLE BRANCH(
	ID INT PRIMARY KEY, 
	BRANCH_NAME NVARCHAR(MAX) NOT NULL,
	BRANCH_LOCATION NVARCHAR(MAX) NOT NULL
);

CREATE TABLE CATEGORY(
	ID INT PRIMARY KEY, 
	CATEGORY_NAME NVARCHAR(MAX) NOT NULL,
);

CREATE TABLE SUPPLIER(
	ID INT PRIMARY KEY, 
	SUPPLIER_NAME NVARCHAR(MAX) NOT NULL,  
	SUPPLIER_LOCATION NVARCHAR(MAX) NOT NULL, 
	PHONE NVARCHAR(MAX) NULL,
);

CREATE TABLE PRODUCT(
	ID INT PRIMARY KEY, 
	PRODUCT_NAME NVARCHAR(MAX) NOT NULL, 
	DETAIL TEXT NOT NULL, 
	ID_CATEGORY INT ,
	EXPIRY DATE NOT NULL,
	IMAGE_PRODUCT NVARCHAR(MAX) NULL,
	FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORY(ID)
);

CREATE TABLE OUTBILL(
	ID INT PRIMARY KEY,
	ID_BRANCH INT NOT NULL, 
	BILL_STATUS NVARCHAR(MAX) NULL , 
	TOTAL BIGINT NULL, 
	CREATE_TIME DATE NOT NULL,
	FOREIGN KEY (ID_BRANCH) REFERENCES BRANCH(ID)
);

CREATE TABLE INBILL(
	ID INT PRIMARY KEY,
	ID_SUPPLIER INT NOT NULL, 
	BILL_STATUS NVARCHAR(MAX) NULL, 
	TOTAL BIGINT NULL, 
	CREATE_TIME DATE NOT NULL,
	FOREIGN KEY (ID_SUPPLIER) REFERENCES SUPPLIER(ID)
);

CREATE TABLE DETAIL_OUTBILL(
	ID_OUTBILL INT , 
	ID_PRODUCT INT ,
	AMOUNT INT , 
	PRIMARY KEY (ID_OUTBILL, ID_PRODUCT),
	FOREIGN KEY (ID_OUTBILL) REFERENCES OUTBILL(ID),
	FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT(ID)
);

CREATE TABLE DETAIL_INBILL(
	ID_INBILL INT , 
	ID_PRODUCT INT,
	AMOUNT INT, 
	COST BIGINT,
	PRIMARY KEY (ID_INBILL, ID_PRODUCT),
	FOREIGN KEY (ID_INBILL) REFERENCES INBILL(ID),
	FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT(ID)
);

CREATE TABLE LIST_PRODUCT(
	ID INT PRIMARY KEY,
	PRODUCT_NAME NVARCHAR(MAX) NOT NULL, 
	EXPIRY INT NOT NULL,
	ID_CATEGORY INT, 
	DETAIL NVARCHAR(MAX) NULL,
	IMAGE_PRODUCT NVARCHAR(MAX) NULL,
	CONSTRAINT FK_LISTPRODUCT_CATEGORY FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORY(ID) 
);

ALTER TABLE PRODUCT ADD AMOUNT INT NULL;
ALTER TABLE PRODUCT ADD UNIT NVARCHAR(MAX) NULL;

ALTER TABLE PRODUCT DROP COLUMN ID_CATEGORY 
ALTER TABLE PRODUCT DROP CONSTRAINT FK__PRODUCT__ID_CATE__412EB0B6;
ALTER TABLE PRODUCT DROP COLUMN PRODUCT_NAME;
ALTER TABLE PRODUCT DROP COLUMN DETAIL;
ALTER TABLE PRODUCT DROP COLUMN EXPIRY;

ALTER TABLE PRODUCT ADD ID_LIST INT NULL;
ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRODUCT_LIST FOREIGN KEY (ID_LIST) REFERENCES LIST_PRODUCT(ID)